backend:
  name: git-gateway
  branch: master

media_folder: "public/assets/img/uploads"
public_folder: "assets/img/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URI", name: "uri", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Meta Title", name: "metaTitle", widget: "string"}
      - {label: "Meta Desc", name: "metaDescription", widget: "string"}
      - {label: "Meta Keywords", name: "metaKeywords", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}